dataset:
  name: ODE_Lorenz
  pair_id: [1,2,3,4,5,6,7,8,9]
model:
  name: AR
  train_split: 0.8
  seed: 0
  n_trials: 3
  method: 'constant'
hyperparameters: # Specify hyperparameters and ranges
  POD_modes:
    type: randint
    lower_bound: 3
    upper_bound: 3
  lag:
    type: randint
    lower_bound: 1
    upper_bound: 50
  poly_degree:
    type: randint
    lower_bound: 1
    upper_bound: 5
  trend:
    type: choice
    values: ["n", "c", "t", "ct"]
  seasonal:
    type: choice
    values: [true, false]
  use_arima:
    type: choice
    values: [true, false]
  d:
    type: randint
    lower_bound: 0
    upper_bound: 2
  q:
    type: randint
    lower_bound: 0
    upper_bound: 2